// Generates agent-specific adapters from the canonical agent config.
//
// Canonical (edit these):
//   AGENTS.md                      (section between copilot markers is mirrored)
//   .agents/rules/<name>.md        (frontmatter: description, paths)
//   .agents/skills/<name>/SKILL.md (validated only)
//
// Generated (never edit):
//   .claude/rules/<name>.md                      Claude Code path-scoped rules
//   .cursor/rules/<name>.mdc                     Cursor file-scoped rules
//   .github/instructions/<name>.instructions.md  Copilot path-specific instructions
//   .github/copilot-instructions.md              Copilot repository-wide instructions
//
// Usage:
//   fvm dart run tool/agents/sync_agent_config.dart          write adapters
//   fvm dart run tool/agents/sync_agent_config.dart --check  exit 1 if anything is stale
import 'dart:io';

const _marker = 'GENERATED by tool/agents/sync_agent_config.dart';
const _copilotStart = '<!-- copilot:start -->';
const _copilotEnd = '<!-- copilot:end -->';

final _root = File.fromUri(Platform.script).parent.parent.parent;

void main(List<String> args) {
  final check = args.contains('--check');
  final errors = <String>[];
  final expected = <String, String>{};

  final rules = _readRules(errors);
  for (final rule in rules) {
    final note = '<!-- $_marker from .agents/rules/${rule.name}.md. Do not edit. -->';
    expected['.claude/rules/${rule.name}.md'] =
        '---\npaths:\n${rule.paths.map((p) => '  - "$p"').join('\n')}\n---\n$note\n\n${rule.body}';
    expected['.cursor/rules/${rule.name}.mdc'] =
        '---\ndescription: ${rule.description}\nglobs: ${rule.paths.join(',')}\n'
        'alwaysApply: false\n---\n$note\n\n${rule.body}';
    expected['.github/instructions/${rule.name}.instructions.md'] =
        '---\napplyTo: "${rule.paths.join(',')}"\n---\n$note\n\n${rule.body}';
  }

  final copilot = _copilotInstructions(errors);
  if (copilot != null) expected['.github/copilot-instructions.md'] = copilot;

  _validateSkills(errors);

  final stale = <String>[];
  expected.forEach((path, content) {
    final file = File('${_root.path}/$path');
    if (file.existsSync() && file.readAsStringSync() == content) return;
    stale.add(path);
    if (!check) {
      file.parent.createSync(recursive: true);
      file.writeAsStringSync(content);
    }
  });

  for (final dir in ['.claude/rules', '.cursor/rules', '.github/instructions']) {
    final directory = Directory('${_root.path}/$dir');
    if (!directory.existsSync()) continue;
    for (final file in directory.listSync().whereType<File>()) {
      final relative = '$dir/${file.uri.pathSegments.last}';
      if (expected.containsKey(relative) || !file.readAsStringSync().contains(_marker)) continue;
      stale.add('$relative (orphaned)');
      if (!check) file.deleteSync();
    }
  }

  _checkSkillsLink(errors, check);

  for (final error in errors) {
    stderr.writeln('error: $error');
  }
  if (check) {
    for (final path in stale) {
      stderr.writeln('stale: $path');
    }
    if (stale.isEmpty && errors.isEmpty) stdout.writeln('Agent config is in sync.');
    exitCode = stale.isEmpty && errors.isEmpty ? 0 : 1;
  } else {
    stdout.writeln(stale.isEmpty ? 'Nothing to update.' : 'Updated:\n  ${stale.join('\n  ')}');
    exitCode = errors.isEmpty ? 0 : 1;
  }
}

class _Rule {
  _Rule(this.name, this.description, this.paths, this.body);

  final String name;
  final String description;
  final List<String> paths;
  final String body;
}

List<_Rule> _readRules(List<String> errors) {
  final dir = Directory('${_root.path}/.agents/rules');
  if (!dir.existsSync()) return [];
  final files = dir.listSync().whereType<File>().where((f) => f.path.endsWith('.md')).toList()
    ..sort((a, b) => a.path.compareTo(b.path));

  final rules = <_Rule>[];
  for (final file in files) {
    final name = file.uri.pathSegments.last.replaceAll('.md', '');
    final parsed = _splitFrontmatter(file.readAsStringSync());
    if (parsed == null) {
      errors.add('.agents/rules/$name.md: missing frontmatter');
      continue;
    }
    String? description;
    final paths = <String>[];
    for (final line in parsed.$1) {
      if (line.startsWith('description:')) {
        description = _unquote(line.substring('description:'.length).trim());
      } else if (line.trimLeft().startsWith('- ')) {
        paths.add(_unquote(line.trimLeft().substring(2).trim()));
      }
    }
    if (description == null || description.isEmpty || paths.isEmpty) {
      errors.add('.agents/rules/$name.md: frontmatter needs "description" and "paths"');
      continue;
    }
    rules.add(_Rule(name, description, paths, parsed.$2.trimLeft()));
  }
  return rules;
}

String? _copilotInstructions(List<String> errors) {
  final agents = File('${_root.path}/AGENTS.md');
  if (!agents.existsSync()) {
    errors.add('AGENTS.md not found');
    return null;
  }
  final text = agents.readAsStringSync();
  final start = text.indexOf(_copilotStart);
  final end = text.indexOf(_copilotEnd);
  if (start < 0 || end < start) {
    errors.add('AGENTS.md: missing $_copilotStart / $_copilotEnd markers');
    return null;
  }
  final section = text.substring(start + _copilotStart.length, end).trim();
  return '<!-- $_marker from AGENTS.md. Do not edit. -->\n'
      '# Copilot instructions\n\n'
      'Full instructions: `AGENTS.md` (workflow, validation levels, project profile). '
      'Path rules: `.agents/rules/`. Skills: `.agents/skills/`.\n\n'
      '$section\n';
}

void _validateSkills(List<String> errors) {
  final dir = Directory('${_root.path}/.agents/skills');
  if (!dir.existsSync()) return;
  final namePattern = RegExp(r'^[a-z0-9]+(-[a-z0-9]+)*$');
  for (final skillDir in dir.listSync().whereType<Directory>()) {
    final folder = skillDir.uri.pathSegments.where((s) => s.isNotEmpty).last;
    final file = File('${skillDir.path}/SKILL.md');
    if (!file.existsSync()) {
      errors.add('.agents/skills/$folder: missing SKILL.md');
      continue;
    }
    final content = file.readAsStringSync();
    final parsed = _splitFrontmatter(content);
    final fields = <String, String>{
      for (final line in parsed?.$1 ?? const <String>[])
        if (line.contains(':') && !line.startsWith(' '))
          line.substring(0, line.indexOf(':')).trim(): _unquote(
            line.substring(line.indexOf(':') + 1).trim(),
          ),
    };
    final name = fields['name'] ?? '';
    final description = fields['description'] ?? '';
    if (name != folder || name.length > 64 || !namePattern.hasMatch(name)) {
      errors.add('.agents/skills/$folder: "name" must equal the folder name (lowercase-hyphen)');
    }
    if (description.isEmpty || description.length > 1024) {
      errors.add('.agents/skills/$folder: "description" must be 1-1024 characters');
    }
    if ('\n'.allMatches(content).length > 500) {
      errors.add('.agents/skills/$folder: SKILL.md exceeds 500 lines');
    }
  }
}

void _checkSkillsLink(List<String> errors, bool check) {
  final link = Link('${_root.path}/.claude/skills');
  const target = '../.agents/skills';
  if (link.existsSync() && link.targetSync() == target) return;
  if (check ||
      FileSystemEntity.typeSync(link.path, followLinks: false) != FileSystemEntityType.notFound) {
    errors.add('.claude/skills must be a symlink to $target');
    return;
  }
  link.createSync(target);
  stdout.writeln('Created symlink .claude/skills -> $target');
}

(List<String>, String)? _splitFrontmatter(String content) {
  final lines = content.split('\n');
  if (lines.isEmpty || lines.first.trim() != '---') return null;
  final end = lines.indexWhere((l) => l.trim() == '---', 1);
  if (end < 0) return null;
  return (lines.sublist(1, end), lines.sublist(end + 1).join('\n'));
}

String _unquote(String value) {
  if (value.length >= 2 &&
      ((value.startsWith('"') && value.endsWith('"')) ||
          (value.startsWith("'") && value.endsWith("'")))) {
    return value.substring(1, value.length - 1);
  }
  return value;
}
