// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive_ce.dart';
import 'package:bashaer_driving/core/services/hive/hive_adapters.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(AnswerLogEntryAdapter());
    registerAdapter(AnswerModelAdapter());
    registerAdapter(CategoryModelAdapter());
    registerAdapter(QuestionModelAdapter());
    registerAdapter(QuestionTypeAdapter());
    registerAdapter(QuizResultModelAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(AnswerLogEntryAdapter());
    registerAdapter(AnswerModelAdapter());
    registerAdapter(CategoryModelAdapter());
    registerAdapter(QuestionModelAdapter());
    registerAdapter(QuestionTypeAdapter());
    registerAdapter(QuizResultModelAdapter());
  }
}
