import 'dart:developer';

import 'package:firebase_core/firebase_core.dart';

import '../../../firebase_options.dart';
import '../../extensions/log_colors_extension.dart';

/// Initialises the Firebase app used for Cloud Firestore and Cloud Storage.
///
/// Options are baked in via `lib/firebase_options.dart` (generated by the
/// FlutterFire CLI), so no runtime keys are needed.
Future<void> initFirebase() async {
  if (Firebase.apps.isNotEmpty) return;

  await Firebase.initializeApp(options: DefaultFirebaseOptions.currentPlatform);
  log('Firebase ready (${DefaultFirebaseOptions.currentPlatform.projectId})'.logWhite);
}
